
INSERT INTO `menus` (`id`, `nome`, `identificador`, `site_id`) VALUES(4, 'Acessibilidade Virtual', 'AcessibilidadeVirtual', 1);

INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(1, 'Página Inicial', 4, '/', NULL, NULL, 2, NULL, 15, 16, 'Página Inicial');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(2, 'Quem somos', 4, '/', NULL, NULL, 2, NULL, 17, 18,  'Quem somos');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(3, 'Notícias', 4, '/noticias', NULL, NULL, 2, NULL, 21, 22, 'Notícias');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(4, 'Eventos', 4, '/eventos', NULL, 4, 2, NULL, 19, 20, 'Eventos');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(5, 'Acessibilidade Web', 4, '/acessibilidade', NULL, NULL, 2, NULL, 23, 32, 'Acessibilidade Web');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(6, 'Pedagógico', 4, '/pedagogico', NULL, NULL, 2, NULL, 33, 42, 'Pedagógico');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(7, 'Tecnologia Assistiva', 4, '/tecnologia-assistiva', NULL, NULL, 2, NULL, 43, 52, 'Tecnologia Assistiva');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(8, 'Contato', 4, '/contato', NULL, NULL, 2, NULL, 53, 54, 'Contato');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(9, 'Projetos acessibilidade web', 4, '/acessibilidade/projetos', NULL, NULL, 2, 5, 28, 29, 'Projetos acessibilidade web');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(10, 'Notícias acessibilidade web', 4, '/acessibilidade', NULL, NULL, 2, 5, 24, 25,  'Notícias acessibilidade web');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(11, 'Dicas acessibilidade web', 4, '/acessibilidade/dicas', NULL, NULL, 2, 5, 26, 27,  'Dicas acessibilidade web');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(12, 'Manuais acessibilidade web', 4, '/acessibilidade/manuais', NULL, NULL, 2, 5, 30, 31,  'Manuais acessibilidade web');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(13, 'Cursos', 4, '/pedagogico/cursos', NULL, NULL, 2, 6, 34, 35,  'Cursos');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(14, 'Objetos de aprendizagem', 4, '/pedagogico/oas', NULL, NULL, 2, 6, 36, 37,  'Objetos de aprendizagem');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(15, 'Notícias pedagógico', 4, '/pedagogico', NULL, NULL, 2, 6, 38, 39,  'Notícias pedagógico');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(16, 'Manuais pedagógico', 4, '/pedagogico/manuais', NULL, NULL, 2, 6, 40, 41,  'Manuais pedagógico');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(17, 'Projetos tecnologia assistiva', 4, '/tecnologia-assistiva/projetos', NULL, NULL, 2, 7, 46, 47, 'Projetos tecnologia assistiva');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(18, 'Notícias tecnologia assistiva', 4, '/tecnologia-assistiva', NULL, NULL, 2, 7, 48, 49, 'Notícias tecnologia assistiva');
INSERT INTO `menu_itens` (`id`, `nome`, `menu_id`, `link`, `pagina_id`, `categoria_id`, `bm_tipo_id`, `parent_id`, `lft`, `rght`, `identificador`) VALUES(19, 'Manuais tecnologia assistiva', 4, '/tecnologia-assistiva/manuais', NULL, NULL, 2, 7, 50, 51, 'Manuais tecnologia assistiva');